[nginx-http-cc]
enabled = true
chain = DOCKER-USER
port = http,https
filter = nginx-http-cc
action = %(action_mwl)s
maxretry = 100
findtime = 10m
bantime = 1h
logpath = /var/lib/docker/containers/cdd5c7dbe272b0e6ca399186bc604aef8e2ef2df2d7337b9fc1e255d168c7046/cdd5c7dbe272b0e6ca399186bc604aef8e2ef2df2d7337b9fc1e255d168c7046-json.log
