# 显示的定义一个 default server
server {
  server_name _;
  listen 80 default_server;
  listen [::]:80 default_server;
  listen 443 ssl default_server;
  listen [::]:443 ssl default_server;

  ssl_certificate         ssl/babudiu.com.crt;
  ssl_certificate_key     ssl/babudiu.com.key;

  return 403; # 403 forbidden
}
    
