server {
    listen       80;
    listen       443 ssl;
    server_name  src.babudiu.com;

    ssl_certificate         ssl/babudiu.com.crt;
    ssl_certificate_key     ssl/babudiu.com.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    error_page 497  https://$host$request_uri;
 
    if ( $scheme = http ){
        rewrite ^(/.*)$ https://$host$1 permanent;
    }

    #防止乱码，需要加上编码
    charset utf-8;
 
    location / {
        root   /src;
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
    }
}
